tag = "octoguns-actions"
writes = [
    "octoguns-CharacterPosition",
    "octoguns-Character",
    "octoguns-Map",
    "octoguns-MapObjects",
    "octoguns-Session",
    "octoguns-SessionMeta",
    "octoguns-Bullet",

]
