tag = "octoguns-start"
writes = [
    "octoguns-CharacterPosition",
    "octoguns-CharacterModel",
    "octoguns-Map",
    "octoguns-MapObjects",
    "octoguns-Session",
    "octoguns-SessionMeta",
    "octoguns-Bullet",
    "octoguns-Global",
    "octoguns-Player"

]
