kind = "DojoModel"
class_hash = "0x18571d59a897476b2ad235151de7a5cce39466feab0af47e68d41ce3f7c96d8"
original_class_hash = "0x18571d59a897476b2ad235151de7a5cce39466feab0af47e68d41ce3f7c96d8"
abi = "manifests/dev/base/abis/models/octoguns-SessionPrimitives-29e33ecc.json"
tag = "octoguns-SessionPrimitives"
qualified_path = "octoguns::models::sessions::session_primitives"
manifest_name = "octoguns-SessionPrimitives-29e33ecc"

[[members]]
name = "session_id"
type = "u32"
key = true

[[members]]
name = "bullet_speed"
type = "u32"
key = false

[[members]]
name = "bullet_sub_steps"
type = "u32"
key = false

[[members]]
name = "bullets_per_turn"
type = "u32"
key = false

[[members]]
name = "sub_moves_per_turn"
type = "u32"
key = false

[[members]]
name = "max_distance_per_turn"
type = "u32"
key = false
