kind = "DojoModel"
class_hash = "0x39e6ae568ba31ee834a8ad49221ae8c2722af9c2cb860b4dfa5c5c049db8dcd"
original_class_hash = "0x39e6ae568ba31ee834a8ad49221ae8c2722af9c2cb860b4dfa5c5c049db8dcd"
abi = "manifests/dev/base/abis/models/octoguns-Bullet-69e7a9ab.json"
tag = "octoguns-Bullet"
qualified_path = "octoguns::models::bullet::bullet"
manifest_name = "octoguns-Bullet-69e7a9ab"

[[members]]
name = "bullet_id"
type = "u32"
key = true

[[members]]
name = "coords"
type = "Vec2"
key = false

[[members]]
name = "speed"
type = "u32"
key = false

[[members]]
name = "angle"
type = "u32"
key = false

[[members]]
name = "shot_by"
type = "ContractAddress"
key = false
