kind = "DojoModel"
class_hash = "0x4f062a938b3b4845fca427ae8b1ff891d1fb00e4b5c93a57aa210147e09312f"
original_class_hash = "0x4f062a938b3b4845fca427ae8b1ff891d1fb00e4b5c93a57aa210147e09312f"
abi = "manifests/dev/base/abis/models/octoguns-TurnData-293d224e.json"
tag = "octoguns-TurnData"
qualified_path = "octoguns::models::turndata::turn_data"
manifest_name = "octoguns-TurnData-293d224e"

[[members]]
name = "session_id"
type = "u32"
key = true

[[members]]
name = "turn_number"
type = "u32"
key = true

[[members]]
name = "moves"
type = "TurnMove"
key = false
