kind = "DojoModel"
class_hash = "0x5c56063ed45085f40248fcdf9193e329a90f429095c2a9c65304745ed1f2a69"
original_class_hash = "0x5c56063ed45085f40248fcdf9193e329a90f429095c2a9c65304745ed1f2a69"
abi = "manifests/dev/base/abis/models/octoguns-CharacterPosition-66fdf8ab.json"
tag = "octoguns-CharacterPosition"
qualified_path = "octoguns::models::characters::character_position"
manifest_name = "octoguns-CharacterPosition-66fdf8ab"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "coords"
type = "Vec2"
key = false

[[members]]
name = "max_steps"
type = "u32"
key = false

[[members]]
name = "current_step"
type = "u32"
key = false
