kind = "DojoModel"
class_hash = "0x166e4b805f01fdae39e4f53e8242504ed50cdadcb5ee31df36b9a9693714ca4"
original_class_hash = "0x166e4b805f01fdae39e4f53e8242504ed50cdadcb5ee31df36b9a9693714ca4"
abi = "manifests/dev/base/abis/models/octoguns-MapObjects-393fad91.json"
tag = "octoguns-MapObjects"
qualified_path = "octoguns::models::map::map_objects"
manifest_name = "octoguns-MapObjects-393fad91"

[[members]]
name = "map_object_id"
type = "u32"
key = true

[[members]]
name = "dimensions"
type = "Vec2"
key = false

[[members]]
name = "coords"
type = "Vec2"
key = false
