# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: 
      - 'main'
      - 'deployment'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - id: setup-dojo
        uses: runelabsxyz/setup-dojo@main
        with:
          version: 'v1.0.0-alpha.12'

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build contract
        working-directory: ./contracts
        run: sozo build -P slot

      - name: Test contract
        working-directory: ./contracts
        run: sozo test -P slot
        if: false # Set this to true when we finally have working tests
      
      - name: Deploy contract
        working-directory: ./contracts
        run: sozo migrate apply -P slot
        env: 
          DOJO_ACCOUNT_ADDRESS: ${{ secrets.DOJO_ACCOUNT_ADDRESS }}
          DOJO_PRIVATE_KEY: ${{ secrets.DOJO_PRIVATE_KEY }}

      - name: Install dependencies
        working-directory: ./refactor
        run: bun install --frozen-lockfile
      
      - name: Build frontend for slot
        run: bun run build
        working-directory: ./refactor
        env:
          ENV: slot
          CF_PAGES: '1'
          # For now, isok, but getting an official file at some point would be nice:
          PUBLIC_TORII_URL: https://api.cartridge.gg/x/octoguns-demo/katana
          PUBLIC_RPC_URL: https://api.cartridge.gg/x/octoguns-demo/katana
          PUBLIC_WORLD_ADDRESS: 0x7447477a7c852c946f0b8d13ebdfe0db9e78f3de60ab799320691502b4d32a3
          PUBLIC_BURNER_ADDRESS: 0xe29882a1fcba1e7e10cad46212257fea5c752a4f9b1b1ec683c503a2cf5c8a
          PUBLIC_BURNER_KEY: 0x14d6672dcb4b77ca36a887e9a11cd9d637d5012468175829e9c6e770c61642

      - name: Deploy to cloudflare pages
        working-directory: ./refactor
        run: bun wrangler pages deploy 

