kind = "DojoContract"
class_hash = "0x62c2854bcf830b025420fd46eaedcbc23816662e8ed2ba8b1c3860133f76ecb"
original_class_hash = "0x62c2854bcf830b025420fd46eaedcbc23816662e8ed2ba8b1c3860133f76ecb"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/octoguns-spawn-1acb0980.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-spawn"
systems = ["spawn"]
manifest_name = "octoguns-spawn-1acb0980"
