kind = "DojoContract"
class_hash = "0x6dadc16afdc543a0a122ebe593c133b1a11e41be4a4778d31198644fa674f43"
original_class_hash = "0x6dadc16afdc543a0a122ebe593c133b1a11e41be4a4778d31198644fa674f43"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/octoguns-spawn-1acb0980.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-spawn"
systems = ["spawn"]
manifest_name = "octoguns-spawn-1acb0980"
