kind = "DojoContract"
class_hash = "0x58ee09e2e766d4db122c02521cadcc332133065d44cebef05ddebd0743cfa70"
original_class_hash = "0x58ee09e2e766d4db122c02521cadcc332133065d44cebef05ddebd0743cfa70"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/octoguns-actions-3f08332a.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-actions"
systems = ["move"]
manifest_name = "octoguns-actions-3f08332a"
