kind = "DojoContract"
class_hash = "0x68060a414f3a582884d8bffac2180be29dd820dcd8997c606c953fb2aed335a"
original_class_hash = "0x68060a414f3a582884d8bffac2180be29dd820dcd8997c606c953fb2aed335a"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/octoguns-spawn-1acb0980.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-spawn"
systems = ["spawn"]
manifest_name = "octoguns-spawn-1acb0980"
