kind = "DojoContract"
class_hash = "0x37652893631b82297ff1d0e604fc3e0a8a8c10d3a35b4390b9a614155e66ddc"
original_class_hash = "0x37652893631b82297ff1d0e604fc3e0a8a8c10d3a35b4390b9a614155e66ddc"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/octoguns-start-5506b80f.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-start"
systems = [
    "create_closed",
    "join",
]
manifest_name = "octoguns-start-5506b80f"
