kind = "DojoContract"
class_hash = "0x3c42b1707efc5a44dad7e9f0b6191da708c1042ef397f1267b766a2030aef54"
original_class_hash = "0x3c42b1707efc5a44dad7e9f0b6191da708c1042ef397f1267b766a2030aef54"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/octoguns-actions-3f08332a.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-actions"
systems = ["move"]
manifest_name = "octoguns-actions-3f08332a"
