kind = "DojoContract"
class_hash = "0x22c262a943c21ba54cb71adfc90231d75b5c1de90c9582dbc18ddc6a13e1d73"
original_class_hash = "0x22c262a943c21ba54cb71adfc90231d75b5c1de90c9582dbc18ddc6a13e1d73"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/octoguns-start-5506b80f.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-start"
systems = [
    "create",
    "join",
]
manifest_name = "octoguns-start-5506b80f"
