kind = "DojoContract"
class_hash = "0x13eed46d5acf1c35b4de3e6bd5866f175497ad378e7ebc72cf3bd2f448caf47"
original_class_hash = "0x13eed46d5acf1c35b4de3e6bd5866f175497ad378e7ebc72cf3bd2f448caf47"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/octoguns-spawn-1acb0980.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-spawn"
systems = ["spawn"]
manifest_name = "octoguns-spawn-1acb0980"
