kind = "DojoContract"
class_hash = "0x540fa26c80fabeb8fb46cd961f3fefb42b310bfb2258170c59e4b35c9c160e4"
original_class_hash = "0x540fa26c80fabeb8fb46cd961f3fefb42b310bfb2258170c59e4b35c9c160e4"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/octoguns-start-5506b80f.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-start"
systems = [
    "create_closed",
    "join",
]
manifest_name = "octoguns-start-5506b80f"
