kind = "DojoContract"
class_hash = "0x5f4c1c05458b56c458d30bdc50723329595b6b2b849f4ac6b0b79159c03a5"
original_class_hash = "0x5f4c1c05458b56c458d30bdc50723329595b6b2b849f4ac6b0b79159c03a5"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/octoguns-start-5506b80f.json"
reads = []
writes = []
init_calldata = []
tag = "octoguns-start"
systems = [
    "create",
    "join",
]
manifest_name = "octoguns-start-5506b80f"
